FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip

WORKDIR /app
COPY ./flight_sim/requirements.txt .
RUN pip install -r requirements.txt

CMD ["python3", "flight_sim/simulation.py"]